#name: StoryBook CD
#on:
#  push:
#    branches:
#      - master
#  workflow_dispatch:
#jobs:
#  cd:
#    if: github.repository_owner == 'spaceone-dev'
#    runs-on: ubuntu-latest
#    steps:
#      - name: git clone
#        uses: actions/checkout@v2
#
#      - name: Checkout submodules
#        uses: srt32/git-actions@v0.0.3
#        with:
#          args: git submodule update --init --recursive
#
#      - name: npm install
#        run: npm install
#
#      - name: build
#        run: npm run build:storybook:github
#
#      - name: clean s3 bucket
#        env:
#          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
#          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
#        run: aws s3 rm s3://storybook-developer --recursive
#
#      - name: Upload S3
#        env:
#          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
#          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
#        run: |
#          aws s3 cp \
#          --recursive \
#          --region ap-northeast-2 \
#          --acl public-read \
#          .out s3://storybook-developer
#
#      - name: Invalidate cache
#        env:
#          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
#          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
#        run: |
#          aws cloudfront create-invalidation --distribution-id E2CEFS46KV2Z2A  --paths "/*"
