name: SpaceONE CI tag

on:
  push:
    tags: "**"
  workflow_dispatch:

jobs:
  hello:
    if: github.repository_owner == 'cloudforet-io'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: getTag
      - run: |
          echo ${{ github.ref }}
          echo ${{ github.event }}
          echo ${{ steps.getTag.outputs.tag }}
