name: Update Translation SpreadSheet
on:
  push:
    paths:
      - 'src/translations/language-pack/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spaceone-dev' && github.ref == 'refs/heads/master'
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          cd ./src/translations
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Sync data
        env:
          SHEET_URL: https://docs.google.com/spreadsheets/d/1K81JbXNLtui93caZu_MyQdy8lv5qxyo69AvlKRA98bM
          CREDENTIAL_BASE64: ${{ secrets.CREDENTIAL_BASE64 }}
          DATA_SHEET_NAME: origin
          SYNC_SHEET_NAME: data
          META_SHEET_NAME: meta
          UNSYNC_FIELD: unsync
          ID_FIELD: Translation ID
        run: |
          cd ./src/translations
          python3 update_translation.py
